web:
  build: docker/web/
  volumes:
   - ./src:/var/www/html
  links:
  - db
  ports:
  - "80:80"
db:
  image: mysql:latest
  ports:
  - "3306:3306"
  environment:
    MYSQL_DATABASE: symfony_db
    MYSQL_USER: root
    MYSQL_ROOT_PASSWORD: root
